
import { Project, Producer, User, ChatSession } from './types';
import { calculateProjectFinancials } from './utils/financial';

export const COLORS = {
  primary: '#4B5320',
  secondary: '#8B4513',
  accent: '#D2B48C',
  bg: '#FDFBF7',
};

export const URUGUAY_DEPARTMENTS = [
  'Artigas', 'Canelones', 'Cerro Largo', 'Colonia', 'Durazno', 'Flores', 'Florida', 'Lavalleja', 'Maldonado', 'Montevideo', 'Paysandú', 'Río Negro', 'Rivera', 'Rocha', 'Salto', 'San José', 'Soriano', 'Tacuarembó', 'Treinta y Tres'
];

export const MOCK_PRODUCER_FREE: Producer = {
  name: 'Carlos Rodríguez',
  email: 'carlos.rodriguez@agro.uy',
  phone: '098765432',
  headline: 'Productor Ganadero con enfoque en Engorde Tradicional',
  bio: 'Trabajo campo natural en el centro del país. Busco capital para completar ciclos de invernada de forma eficiente.',
  dicose: '210512345',
  experienceYears: 12,
  locationDetails: 'Florida',
  guaranteeType: 'Fiador',
  plan: 'free',
  coverImage: 'https://i.ibb.co/3Y0FRXyr/campo.jpg',
  experience: [{ establishment: 'Campo El Paraíso', role: 'Productor', period: '2015 - Actualidad', achievement: 'Mantenimiento de stock constante.' }],
  education: ['Bachillerato Agrario'],
  skills: ['Invernada', 'Sanidad Animal'],
  socialLinks: {
    facebook: 'https://facebook.com/carlos.agro',
    instagram: 'https://instagram.com/carlos.agro'
  }
};

export const MOCK_PRODUCER_PREMIUM: Producer = {
  name: 'Elena Silva',
  email: 'elena.silva@agrotec.com.uy',
  phone: '097111222',
  headline: 'Especialista en Ciclos Completos y Exportación - Socia PRO',
  bio: 'Ingeniera Agrónoma con foco en alta tecnología y bienestar animal. Exportamos genética de calidad superior.',
  dicose: '120456789',
  experienceYears: 18,
  locationDetails: 'Soriano',
  guaranteeType: 'Prenda',
  plan: 'premium',
  coverImage: 'https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?q=80&w=1200&auto=format&fit=crop',
  experience: [{ establishment: 'AgroTec Soriano', role: 'Directora Técnica', period: '2010 - 2024', achievement: 'Lideramos 3 proyectos exitosos de exportación directa.' }],
  education: ['Ingeniería Agronómica - UDELAR'],
  skills: ['Genética', 'Trazabilidad', 'Gestión Financiera'],
  documents: [{ id: 'd1', name: 'Historial de Pagos 2023', type: 'Otros', url: '#' }, { id: 'd2', name: 'Certificado Sanitario 2024', type: 'Otros', url: '#' }],
  socialLinks: {
    linkedin: 'https://linkedin.com/in/elenasilva-agro',
    x: 'https://x.com/elenasilva_agro'
  }
};

export const QUICK_USERS: User[] = [
  { id: 'u1', name: 'Juan Pérez', phoneNumber: '099123456', verificationLevel: 1 },
  { id: 'u2', name: 'Carlos Rodríguez', phoneNumber: '098765432', verificationLevel: 2, producerData: MOCK_PRODUCER_FREE },
  { id: 'u3', name: 'Elena Silva', phoneNumber: '097111222', verificationLevel: 3, producerData: MOCK_PRODUCER_PREMIUM }
];

export const MOCK_CHATS: ChatSession[] = [
  { id: 'c1', participantName: 'Roberto Gómez', projectTitle: 'Recría Premium para Exportación', lastMessage: 'Perfecto, mañana te llamo tipo 10 para coordinar la visita.', timestamp: '10:45 AM', unread: true, messages: [] },
  { id: 'c2', participantName: 'Juan Pérez', projectTitle: 'Engorde de Novillos - Ciclo Rápido', lastMessage: '¿Recibiste la ficha técnica actualizada?', timestamp: 'Ayer', unread: false, messages: [] }
];

export const MOCK_PROJECTS: Project[] = ([
  {
    id: '1000',
    category: 'livestock',
    subCategory: 'Novillos 1-2 años',
    title: 'Engorde de Novillos - Ciclo Rápido',
    amount: 72000,
    amountRaised: 25000,
    minTicket: 1000,
    deadline: '2024-12-30',
    term: '6 meses',
    department: 'Florida',
    zone: 'Sarandí Grande',
    guaranteeLabel: 'Contrato Simple',
    image: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?q=80&w=800&auto=format&fit=crop',
    description: 'Invernada tradicional de novillos de 2 años sobre campo natural mejorado. Contamos con amplia experiencia en la zona y un historial de engorde eficiente.',
    producer: MOCK_PRODUCER_FREE,
    investors: [],
    status: 'active',
    projections: { irr: 12.0, npv: 450, grossMargin: 2500, initialInvestment: 72000, expectedExitValue: 85000, marketStatus: 'green', monthlyCashFlow: [] },
    livestockData: { entryWeight: 300, purchasePriceKg: 3.20, healthCostHead: 15, targetExitWeight: 480, salePriceKg: 5.42, headCount: 75, hectares: 60, pastureType: 'Campo Natural' },
    gallery: [
      'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?q=80&w=800&auto=format&fit=crop',
      'https://i.ibb.co/3Y0FRXyr/campo.jpg'
    ]
  },
  {
    id: '1001',
    category: 'livestock',
    subCategory: 'Terneros 140-180kg',
    title: 'Recría Premium para Exportación',
    amount: 90880,
    amountRaised: 38000,
    minTicket: 5000,
    deadline: '2025-01-15',
    term: '12 meses',
    department: 'Soriano',
    zone: 'Mercedes',
    guaranteeLabel: 'Prenda sobre Activo PRO',
    image: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?q=80&w=800&auto=format&fit=crop',
    description: 'Proyecto de alta eficiencia sobre pasturas de alfalfa. SocioRural PRO Verificado. Incluimos trazabilidad completa y genética de punta para mercado externo.',
    producer: MOCK_PRODUCER_PREMIUM,
    investors: [{ id: 'i1', name: 'Inversor Anónimo', amount: 38000, status: 'accepted', date: '2024-11-20' }],
    status: 'active',
    projections: { irr: 16.5, npv: 3200, grossMargin: 9500, initialInvestment: 90880, expectedExitValue: 115000, marketStatus: 'green', monthlyCashFlow: [] },
    livestockData: { entryWeight: 160, purchasePriceKg: 3.55, healthCostHead: 20, targetExitWeight: 320, salePriceKg: 5.55, headCount: 160, hectares: 90, pastureType: 'Pasturas Mejoradas' },
    gallery: [
      'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?q=80&w=1200&auto=format&fit=crop'
    ]
  },
  {
    id: '1002',
    category: 'agriculture',
    subCategory: 'Soja',
    title: 'Campaña Soja 2026 - Soriano',
    amount: 320000,
    amountRaised: 0,
    minTicket: 10000,
    deadline: '2025-05-15',
    term: '6 meses',
    department: 'Soriano',
    zone: 'Dolores',
    guaranteeLabel: 'Contrato de Producción PRO',
    image: 'https://images.unsplash.com/photo-1595113316349-9fa4eb24f884?q=80&w=800&auto=format&fit=crop',
    description: 'Producción de soja de primera en el núcleo agrícola del país. Suelos con alto IC (Coneat) y paquete tecnológico de vanguardia para asegurar rinde.',
    producer: MOCK_PRODUCER_PREMIUM,
    investors: [],
    status: 'active',
    projections: { irr: 14.2, npv: 12000, grossMargin: 45000, initialInvestment: 320000, expectedExitValue: 365000, marketStatus: 'green', monthlyCashFlow: [] },
    agricultureData: { implCostHa: 800, hectares: 400, expectedYield: 3200, salePriceUnit: 410, unit: 'ton' },
    gallery: ['https://images.unsplash.com/photo-1595113316349-9fa4eb24f884?q=80&w=800&auto=format&fit=crop']
  },
  {
    id: '1003',
    category: 'agriculture',
    subCategory: 'Tomate',
    title: 'Producción de Tomate en Invernadero',
    amount: 15000,
    amountRaised: 8000,
    minTicket: 500,
    deadline: '2025-06-30',
    term: '8 meses',
    department: 'Canelones',
    zone: 'Progreso',
    guaranteeLabel: 'Seguro Agrícola incluido',
    image: 'https://images.unsplash.com/photo-1592841200221-a6898f307bac?q=80&w=800&auto=format&fit=crop',
    description: 'Producción intensiva de tomate perita bajo cubierta. Tecnología de riego por goteo y manejo integrado de plagas para abastecimiento local.',
    producer: MOCK_PRODUCER_FREE,
    investors: [],
    status: 'active',
    projections: { irr: 22.5, npv: 2500, grossMargin: 12000, initialInvestment: 15000, expectedExitValue: 27000, marketStatus: 'green', monthlyCashFlow: [] },
    agricultureData: { implCostHa: 15000, hectares: 1, expectedYield: 60, salePriceUnit: 1.65, unit: 'kg' },
    gallery: ['https://images.unsplash.com/photo-1592841200221-a6898f307bac?q=80&w=800&auto=format&fit=crop']
  },
  {
    id: '1004',
    category: 'agriculture',
    subCategory: 'Arroz',
    title: 'Ciclo Arrocero - Cuenca del Este',
    amount: 225000,
    amountRaised: 45000,
    minTicket: 5000,
    deadline: '2025-04-10',
    term: '8 meses',
    department: 'Rocha',
    zone: 'Lascano',
    guaranteeLabel: 'Prenda sobre Cosecha PRO',
    image: 'https://images.unsplash.com/photo-1536633100234-58e11a684525?q=80&w=800&auto=format&fit=crop',
    description: 'Producción de arroz de exportación. Sistema de riego por inundación optimizado y cercanía a plantas de procesamiento líderes.',
    producer: MOCK_PRODUCER_PREMIUM,
    investors: [],
    status: 'active',
    projections: { irr: 11.8, npv: 8500, grossMargin: 35000, initialInvestment: 225000, expectedExitValue: 260000, marketStatus: 'green', monthlyCashFlow: [] },
    agricultureData: { implCostHa: 2250, hectares: 100, expectedYield: 9000, salePriceUnit: 480, unit: 'ton' },
    gallery: ['https://images.unsplash.com/photo-1536633100234-58e11a684525?q=80&w=800&auto=format&fit=crop']
  },
  {
    id: '1005',
    category: 'agriculture',
    subCategory: 'Cebolla',
    title: 'Cebolla de Calidad - Exportación',
    amount: 28000,
    amountRaised: 5000,
    minTicket: 1000,
    deadline: '2025-07-20',
    term: '7 meses',
    department: 'San José',
    zone: 'Libertad',
    guaranteeLabel: 'Historial de Rindes Verificado',
    image: 'https://images.unsplash.com/photo-1508747703725-719777637510?q=80&w=800&auto=format&fit=crop',
    description: 'Cultivo de cebolla para mercado interno y exportación a Brasil. Foco en sanidad y tamaño de bulbo premium.',
    producer: MOCK_PRODUCER_FREE,
    investors: [],
    status: 'active',
    projections: { irr: 18.2, npv: 3200, grossMargin: 15000, initialInvestment: 28000, expectedExitValue: 43000, marketStatus: 'green', monthlyCashFlow: [] },
    agricultureData: { implCostHa: 7000, hectares: 4, expectedYield: 35, salePriceUnit: 1.35, unit: 'kg' },
    gallery: ['https://images.unsplash.com/photo-1508747703725-719777637510?q=80&w=800&auto=format&fit=crop']
  },
  {
    id: '1006',
    category: 'agriculture',
    subCategory: 'Maíz',
    title: 'Maíz de Segunda - Riego por Pivote',
    amount: 145000,
    amountRaised: 0,
    minTicket: 7000,
    deadline: '2025-06-01',
    term: '5 meses',
    department: 'Colonia',
    zone: 'Tarariras',
    guaranteeLabel: 'Equipo de Riego como Respaldo',
    image: 'https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?q=80&w=800&auto=format&fit=crop',
    description: 'Siembra de maíz sobre rastrojo de invierno con riego suplementario para asegurar pisos de rendimiento superiores a la media nacional.',
    producer: MOCK_PRODUCER_PREMIUM,
    investors: [],
    status: 'active',
    projections: { irr: 13.5, npv: 5200, grossMargin: 25000, initialInvestment: 145000, expectedExitValue: 170000, marketStatus: 'green', monthlyCashFlow: [] },
    agricultureData: { implCostHa: 1050, hectares: 138, expectedYield: 8500, salePriceUnit: 215, unit: 'ton' },
    gallery: ['https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?q=80&w=800&auto=format&fit=crop']
  },
  {
    id: '1007',
    category: 'agriculture',
    subCategory: 'Morrón',
    title: 'Morrón de Estación - Salto Hortícola',
    amount: 18500,
    amountRaised: 2000,
    minTicket: 1000,
    deadline: '2025-08-15',
    term: '9 meses',
    department: 'Salto',
    zone: 'Colonia 18 de Julio',
    guaranteeLabel: 'Contrato Facilitado por SR',
    image: 'https://images.unsplash.com/photo-1506368249639-73a05d6f6488?q=80&w=800&auto=format&fit=crop',
    description: 'Producción temprana de morrón rojo y verde para primicia en el Mercado Modelo. Microclima ideal del norte uruguayo.',
    producer: MOCK_PRODUCER_FREE,
    investors: [],
    status: 'active',
    projections: { irr: 25.0, npv: 3800, grossMargin: 18000, initialInvestment: 18500, expectedExitValue: 36500, marketStatus: 'green', monthlyCashFlow: [] },
    agricultureData: { implCostHa: 9250, hectares: 2, expectedYield: 45, salePriceUnit: 1.80, unit: 'kg' },
    gallery: ['https://images.unsplash.com/photo-1506368249639-73a05d6f6488?q=80&w=800&auto=format&fit=crop']
  },
  {
    id: '1008',
    category: 'livestock',
    subCategory: 'Novillos 2-3 años',
    title: 'Novillos Cuota 481 - Pasturas',
    amount: 145200,
    amountRaised: 20000,
    minTicket: 5000,
    deadline: '2025-01-05',
    term: '10 meses',
    department: 'Durazno',
    zone: 'Sarandí del Yí',
    guaranteeLabel: 'Contrato Verificado PRO',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=800&auto=format&fit=crop',
    description: 'Terminación de novillos pesados para la Cuota 481. Establecimiento de 150 hectáreas con excelentes pasturas de raigrás.',
    producer: MOCK_PRODUCER_PREMIUM,
    investors: [],
    status: 'active',
    projections: { irr: 15.2, npv: 5100, grossMargin: 12000, initialInvestment: 145200, expectedExitValue: 180000, marketStatus: 'green', monthlyCashFlow: [] },
    livestockData: { entryWeight: 400, purchasePriceKg: 3.30, healthCostHead: 15, targetExitWeight: 550, salePriceKg: 5.55, headCount: 110, hectares: 100, pastureType: 'Pasturas Mejoradas' },
    gallery: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=800&auto=format&fit=crop']
  },
  {
    id: '1009',
    category: 'livestock',
    subCategory: 'Vaca de Invernada',
    title: 'Invernada de Vacas - Ciclo Corto',
    amount: 39330,
    amountRaised: 12000,
    minTicket: 2000,
    deadline: '2024-12-15',
    term: '5 meses',
    department: 'Salto',
    zone: 'San Antonio',
    guaranteeLabel: 'Contrato de Matchmaking',
    image: 'https://i.ibb.co/7xBKQT3C/vaca.jpg',
    description: 'Engorde rápido de vacas fallas sobre campo natural y rastrojo de sorgo. Oportunidad de rotación rápida de capital.',
    producer: MOCK_PRODUCER_FREE,
    investors: [],
    status: 'active',
    projections: { irr: 14.0, npv: 800, grossMargin: 4500, initialInvestment: 39330, expectedExitValue: 48000, marketStatus: 'green', monthlyCashFlow: [] },
    livestockData: { entryWeight: 380, purchasePriceKg: 2.30, healthCostHead: 10, targetExitWeight: 480, salePriceKg: 4.95, headCount: 45, hectares: 50, pastureType: 'Campo Natural' },
    gallery: ['https://i.ibb.co/7xBKQT3C/vaca.jpg']
  },
  {
    id: '1010',
    category: 'livestock',
    subCategory: 'Ovinos',
    title: 'Producción Ovina Merino - Lana Fina',
    amount: 23625,
    amountRaised: 15000,
    minTicket: 1500,
    deadline: '2025-02-28',
    term: '12 meses',
    department: 'Rivera',
    zone: 'Vichadero',
    guaranteeLabel: 'Contrato Verificado PRO',
    image: 'https://images.unsplash.com/photo-1484557985045-edf25e08da73?q=80&w=800&auto=format&fit=crop',
    description: 'Explotación ovina enfocada en lana fina de exportación y carne ovina. Merino Australiano de alta calidad.',
    producer: MOCK_PRODUCER_PREMIUM,
    investors: [],
    status: 'active',
    projections: { irr: 18.0, npv: 1200, grossMargin: 6500, initialInvestment: 23625, expectedExitValue: 32500, marketStatus: 'green', monthlyCashFlow: [] },
    livestockData: { entryWeight: 45, purchasePriceKg: 2.10, healthCostHead: 12, targetExitWeight: 60, salePriceKg: 4.80, headCount: 250, hectares: 80, pastureType: 'Campo Natural' },
    gallery: ['https://images.unsplash.com/photo-1484557985045-edf25e08da73?q=80&w=800&auto=format&fit=crop']
  },
  {
    id: '1011',
    category: 'livestock',
    subCategory: 'Vaquillonas 1-2 años',
    title: 'Vaquillonas Braford de Reposición',
    amount: 67200,
    amountRaised: 5000,
    minTicket: 3000,
    deadline: '2025-01-20',
    term: '14 meses',
    department: 'Paysandú',
    zone: 'Quebracho',
    guaranteeLabel: 'Prenda sobre Hacienda',
    image: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?q=80&w=800&auto=format&fit=crop',
    description: 'Recría de vaquillonas Braford para venta como vientres preñados. Manejo bajo pastoreo rotativo Voisin.',
    producer: MOCK_PRODUCER_PREMIUM,
    investors: [],
    status: 'active',
    projections: { irr: 17.5, npv: 2800, grossMargin: 8200, initialInvestment: 67200, expectedExitValue: 85000, marketStatus: 'green', monthlyCashFlow: [] },
    livestockData: { entryWeight: 280, purchasePriceKg: 3.00, healthCostHead: 25, targetExitWeight: 420, salePriceKg: 5.40, headCount: 80, hectares: 70, pastureType: 'Pasturas Mejoradas' },
    gallery: ['https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?q=80&w=800&auto=format&fit=crop']
  },
  {
    id: '1012',
    category: 'livestock',
    subCategory: 'Terneros <140kg',
    title: 'Terneros Holando - Invernada Mixta',
    amount: 50820,
    amountRaised: 10000,
    minTicket: 1000,
    deadline: '2024-12-20',
    term: '8 meses',
    department: 'Lavalleja',
    zone: 'Solís de Mataojo',
    guaranteeLabel: 'Contrato Simple',
    image: 'https://images.unsplash.com/photo-1527112803112-482005211d8e?q=80&w=800&auto=format&fit=crop',
    description: 'Compra de terneros livianos para invernada en zona de sierras. Enfoque en volumen.',
    producer: MOCK_PRODUCER_FREE,
    investors: [],
    status: 'active',
    projections: { irr: 13.5, npv: 1100, grossMargin: 5200, initialInvestment: 50820, expectedExitValue: 65000, marketStatus: 'green', monthlyCashFlow: [] },
    livestockData: { entryWeight: 120, purchasePriceKg: 3.85, healthCostHead: 15, targetExitWeight: 260, salePriceKg: 5.15, headCount: 110, hectares: 90, pastureType: 'Campo Natural' },
    gallery: ['https://images.unsplash.com/photo-1527112803112-482005211d8e?q=80&w=800&auto=format&fit=crop']
  },
  {
    id: '1013',
    category: 'livestock',
    subCategory: 'Novillos +3 años',
    title: 'Terminación a Corral - Engorde Final',
    amount: 155000,
    amountRaised: 45000,
    minTicket: 7000,
    deadline: '2024-12-30',
    term: '4 meses',
    department: 'Río Negro',
    zone: 'Young',
    guaranteeLabel: 'Fideicomiso Ganadero PRO',
    image: 'https://images.unsplash.com/photo-1471193945509-9ad0617afabf?q=80&w=800&auto=format&fit=crop',
    description: 'Terminación intensiva de novillos pesados a corral. 90-100 días de encierro para exportación.',
    producer: MOCK_PRODUCER_PREMIUM,
    investors: [],
    status: 'active',
    projections: { irr: 14.5, npv: 4200, grossMargin: 11500, initialInvestment: 155000, expectedExitValue: 185000, marketStatus: 'green', monthlyCashFlow: [] },
    livestockData: { entryWeight: 500, purchasePriceKg: 3.10, healthCostHead: 100, targetExitWeight: 600, salePriceKg: 5.75, headCount: 100, hectares: 20, pastureType: 'Suplementación/Confinamiento' },
    gallery: ['https://images.unsplash.com/photo-1471193945509-9ad0617afabf?q=80&w=800&auto=format&fit=crop']
  }
] as any[]).map(p => {
  const financials = calculateProjectFinancials(p);
  return {
    ...p,
    amount: financials.amount,
    projections: {
      ...p.projections,
      initialInvestment: financials.initialInvestment,
      expectedExitValue: financials.expectedExitValue,
      grossMargin: financials.grossMargin,
      marketStatus: financials.marketStatus
    }
  };
});
